"use client";

import Header from "@/components/(ui)/Header";
import TitleCard from "@/components/Card.tsx/TitleCard";

const DUMMY_DATA = [
  {
    tags: ["React", "Next.js", "TypeScript", "Chakra UI"],
    title: "Create Next App",
    description: "Generated by create next app",
    date: "2023-01-01",
    readTime: "10 min read",
    imageUrl: "/rock.png",
  },
  {
    tags: ["React", "Next.js", "TypeScript", "Chakra UI"],
    title: "Create Next App",
    description: "Generated by create next app",
    date: "2023-01-01",
    readTime: "10 min read",
    imageUrl: "/rock.png",
  },
  {
    tags: ["React", "Next.js", "TypeScript", "Chakra UI"],
    title: "Create Next App",
    description: "Generated by create next app",
    date: "2023-01-01",
    readTime: "10 min read",
    imageUrl: "/rock.png",
  },
];

export default function Home() {
  return (
    <>
      <Header />
      {DUMMY_DATA.map((data, index) => {
        return (
          <TitleCard
            key={index}
            tags={data.tags}
            title={data.title}
            description={data.description}
            date={data.date}
            readTime={data.readTime}
            imageUrl={data.imageUrl}
          />
        );
      })}
    </>
  );
}
