import Header from "@/components/(ui)/Header";
import TitleCard from "@/components/Card.tsx/TitleCard";

const DUMMY_DATA = {
  tags: ["React", "Next.js", "TypeScript", "Chakra UI"],
  title: "Create Next App",
  description: "Generated by create next app",
  date: "2023-01-01",
  readTime: "10 min read",
};

export default function Home() {
  return (
    <>
      <Header />
      <TitleCard
        tags={DUMMY_DATA.tags}
        title={DUMMY_DATA.title}
        description={DUMMY_DATA.description}
        date={DUMMY_DATA.date}
        readTime={DUMMY_DATA.readTime}
      />
    </>
  );
}
